# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "deploy_to_aws"
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
		steps:
			- name: checkout code
			  uses: actions/checkout@v2
			- name: setup ruby
				uses: actions/setup-ruby@v1
			  with:
				  ruby-version: 3.2.2 
			- name: install dependencies
			  run: |
				  gem install bundler
				  bundle install --job 4 --retry 3
			- name: build and test
			  run: |
				  bundle exec rails db:create db:migrate db:seed
				  bundle exec rspec
			- name: precompile assets
				run: |
					rails dartsass:build  
					rails assets:precompile
			- name: deploy to AWS
			  env: 
					AWS_ACCESS_KEY: ENV['AWS_ACCES_KEY']
					AWS_REGION: us-east-1c

				# TODO: when EBS is working, a command to link local code w/ AWS???
				# run: |
				  # AWS commands to deploy to elastic beanstalk


